### ISSUE TITLE
The order of hashed keys in data manager is not deterministic

### ISSUE THREAD

**Issue by charest** [laristra/flecsi#119]
Registering variables in the following order:

```
register_state(mesh, "density",      cells,   real_t, persistent);
register_state(mesh, "pressure",     cells,   real_t, persistent);
register_state(mesh, "internal_energy", cells, real_t, persistent);
register_state(mesh, "temperature",     cells, real_t, persistent);
register_state(mesh, "sound_speed",     cells, real_t, persistent);
```

doesn't guarantee they are stored in that order in the database.  The resulting order the variables are stored in the database (whatever that may be) _should_ be deterministic.  For example, using the following example:

```
for ( auto var : access_type_if(m, real_t, is_persistent_at(m,cells)) )
    std::cout << var.label() << std::end;
```

produces 

```
sound_speed
temperature
density
pressure
internal_energy
```

or 

```
temperature
density
sound_speed
pressure
internal_energy
```

**Comment by nickm319** [comment]
One of the items we are hashing is a pointer (the data client) to determine the final key. I am guessing this is what is causing it. If we need something stable across runs, we'll have to rethink this.

**Comment by charest** [comment]
The data client is a singleton.  If there is only ever one instance, does it still make sense to include it in the hashing?

**Comment by charest** [comment]
Without a deterministic order or keys in the database, regression testing will be difficult.

**Comment by nickm319** [comment]
More precisely, it uses the runtime_id() in data_client.h. The data_t for registering state data is always a singleton, but the data client, will be the mesh  topology, tree topology, etc.

**Comment by junghans** [comment]
One could sort the output first before writing it to a file.

**Comment by charest** [comment]
Of course one could, but that is not very user friendly

**Comment by charest** [comment]
Removing `this` from the hash seams to fix this problem.


diff --git a/flecsi/data/data_client.h b/flecsi/data/data_client.h
index 2f72de9..29d23ed 100644
--- a/flecsi/data/data_client.h
+++ b/flecsi/data/data_client.h
@@ -46,7 +46,7 @@ public:
     data manager.
    */
   uintptr_t runtime_id() const {
-    return reinterpret_cast<uintptr_t>(this+id_);
+    return reinterpret_cast<uintptr_t>(id_);
   } // runtime_id

**Comment by charest** [comment]
Scratch that.  Removing `this` doesn't work.

**Comment by timmah** [comment]
What are you doing that is sensitive to the ordering of the variables?

**Comment by charest** [comment]
When I output field data, I iterate over fields.  The order of the fields is not deterministic, so my output files are constantly diff'ing

**Comment by womeld** [comment]
I think it sounds like bad practice to depend on a deterministic ordering. I think a better idea might be some sort of tag or method that would let you get the behaviour you desire.

Imagine something like this:
for ( auto var : access_type_if(m, real_t, is_persistent_at(m,cells)), "sorted" )

For some notion of sorted.

**Comment by timmah** [comment]
For example, if you're testing that the data manager has the right set of fields, then set might be more useful than vectors:
```
std::set<label_t> expected_keys = {"density","pressure","umami"},
  actual_keys = {};
for(auto & v : access_type_if(...)){
  actual_keys.insert(v.label());
}
EXPECT_EQ(expected_keys,actual_keys);
```

**Comment by charest** [comment]
I'm definitely ok with that.  Let me look into adding that.
