### ISSUE TITLE
mpilegion test are broken

### ISSUE THREAD

**Issue by junghans** [laristra/flecsi#149]
See ab048859613c0609e57197a37cd90b90914e9f4d and build of it:
https://travis-ci.org/losalamos/flecsi/builds/173147206

**Comment by ipdemes** [comment]
I have just uncommented mpilegion tests in the execution branch to see if the pass the docker tests (they pass on my laptop with legion+gasnet built through third-party libraries)

**Comment by junghans** [comment]
It seems losalamos/flecsi-third-party#13 didn't help:
https://travis-ci.org/losalamos/flecsi/builds/177824151

**Comment by junghans** [comment]
Testing this in docker:
```
docker pull flecsi/flecsi:fedora_mpilegion
run -it flecsi/flecsi:fedora_mpilegion /bin/bash
cd flecsi/build/
unset TRAVIS
cmake ..
make test
```

**Comment by ipdemes** [comment]
The issue is related to the way GASNET (with MPI conduit) finalize MPI. There is nothing we can do for fixing the issue other than changing conduit to the different one  on TRAVIS
