### ISSUE TITLE
Check that legion has the right conduit for our runtime

### ISSUE THREAD

**Issue by junghans** [laristra/flecsi#150]
Missing part of #148.

**Comment by ipdemes** [comment]
I am going to start looking into this. An Idea is to check LegionConfig.cmake for the Gasnet conduit

**Comment by junghans** [comment]
I think we should check for `gasneti_linkconfig_idiotcheck_CORE_MPI` in `liblegion.so` like in:
https://github.com/votca/tools/blob/master/CMakeModules/FindFFTW3.cmake#L42
