### ISSUE TITLE
libflecsi linkage

### ISSUE THREAD

**Issue by junghans** [laristra/flecsi#181]
Currently libflecsi isn't linked against anything, but with making legion a dependency, we need to at least link against liblegion and librealm. This will simplify building apps down the path, e.g. flecsale doesn't need to know if and with which liblegion flecsi was build, this is all stored in the shared library.

As a rule of thumb, to avoid undefined symbols, linking should work with `-Wl,-z,defs` being in `LDFLAGS`.

/cc @charest

**Comment by tuxfan** [comment]
This is no longer relevant.
