### ISSUE TITLE
Implementing the Runtime Context 

### ISSUE THREAD

**Issue by spad12** [laristra/flecsi#19]
So how do we want to do this? Do we want to have different classes for each runtime controlled by compiler-time switches, or do we want to have each runtime specific context inherit from a parent context_t?

**Comment by tuxfan** [comment]
?I would use compile-time selection and avoid dynamic polymorphism if possible.  If there is a good reason to do it dynamically, then it's fine...


--
Dr.-Ing. Benjamin Karl Bergen, M.Sc.
Applied Computer Science (CCS-7)

Los Alamos National Laboratory
P.O. Box 1663, MS B287
Los Alamos, NM 87545

505-667-1699 (w)
505-795-2275 (c)
505-665-4972 (f)
________________________________

**Comment by spad12** [comment]
Alright, so what I've done is leave your version of the context mostly alone so it will be used as a default policy. I created a new file for the specialization of the context on legion_execution_policy_t.
