### ISSUE TITLE
Write down 2-D lax-Wendroff algorithm.

### ISSUE THREAD

**Issue by jpietarilagraham** [laristra/flecsi#191]
Define boundary conditions also.

**Comment by jpietarilagraham** [comment]
Boundary conditions will be periodic.


![screen shot 2017-01-11 at 9 12 24 am](https://cloud.githubusercontent.com/assets/19434821/21856138/1e90f17a-d7de-11e6-8289-e7b5fd94e4bb.png)

**Comment by tuxfan** [comment]
Excellent! :-)

Jonathan,
If you are interested, we were discussing adding a MUSCL-Hancock proxy on FleCSI. It would be quite similar to this, although it's a little more complicated. I have an example code that we could start from. This would be a separate mini-project from the sprint with a deadline of the end of the fiscal year.

**Comment by jpietarilagraham** [comment]
Tell me more!
