### ISSUE TITLE
flecsi.h.in file issues

### ISSUE THREAD

**Issue by tuxfan** [laristra/flecsi#196]
Need to figure out at what level certain features are defined. For example, ENABLE_BOOST_PREPROCESSOR conflicts with a previous definition (in cinch) when it is added to flecsi.h.in. This is just a matter of deciding how things should be organized. I'm adding the issue so that we can have a discussion about conventions.

One convention that I propose is that if we have an option ENABLE_FEATURE, the corresponding compile define should be ENABLE_FEATURE (the same). This allows us to write:

#if defined(ENABLE_FEATURE)
   // do something
#endif

**Comment by junghans** [comment]
We could could use a guard to avoid redefinition:
```
#if not defined(XXX)
#cmakedefine ${XXX}
#endif
```

**Comment by tuxfan** [comment]
What about making a cinch.h file that the application project could choose to include? There are several options in cinch that may not be getting captured.

**Comment by charest** [comment]
Nested projects might want to set these options differently, why not tack on the project name, so ENABLE_BOOST_PREPROCESSOR could be PROJECT_ENABLE_BOOST_PREPROCESSOR.  But I see this being a bit cumbersum.

**Comment by tuxfan** [comment]
I don't like that because, if we handle it in a good way, the project wouldn't have to really do anything. What you propose seems redundant.

**Comment by tuxfan** [comment]
Christoph,

You didn't put guards in the flecsi.h.in. Is this the desired way to do this?

**Comment by junghans** [comment]
_ desired_ not sure, but it would help!

**Comment by tuxfan** [comment]
Ok. I don't like putting stuff in cinch. I removed the add_definition from cinch and put the define for Boost into flecsi.h. The reasoning behind this is that the project should decide what defines are meaningful. Since flecsi.h captures the build state, projects that include FleCSI as a sub-project can just include flecsi.h to pick up the defines. We should move anything that is a configuration option into flecsi.h.

**Comment by junghans** [comment]
Hmm, now `flecsi.h` includes `cinch.h`, but the latter does get installed, so that breaks packages depending on flecsi.

**Comment by junghans** [comment]
Fixed in c2698a113d3d6a55596200e374f927d69b6a1c63.
