### ISSUE TITLE
Unnecessary waring from serial driver

### ISSUE THREAD

**Issue by charest** [laristra/flecsi#222]
Is there a reason for this warning when running in serial?

    Warning: You are executing the default specialization driver!
    This driver has no functionality except as a place holder...

**Comment by tuxfan** [comment]
That doesn't mean that you are running in serial. You have to specify a driver if you use the FleCSI runtime drivers (you don't have to do this). This warning indicates that nothing is being executed.

**Comment by charest** [comment]
I set the runtime model to serial.  FLECSI_RUNTIME_MODEL:STRING=serial according to CMakeCache.  What else do I have do set then?

**Comment by tuxfan** [comment]
You have to identify a user driver with -DFLECSI_DRIVER

**Comment by charest** [comment]
Both `-DFLECSI_DRIVER=.../driver.h` and `-DFLECSI_RUNTIME_MODEL_serial` are in fact set but I still get the warning.  How would my code run if it wasn't?

**Comment by tuxfan** [comment]
Oops! This is new. You can probably ignore it for now. I didn't read the warning carefully enough. The specialization driver is a new control point that we added for the move to distributed-memory parallelism.

**Comment by tuxfan** [comment]
If seeing the message itself irritates you, I can send you an email detailing how much I care about your discomfort... ;-)

**Comment by charest** [comment]
The point is do we really need the warning.  It does not bother me, but others might think something is wrong.

**Comment by tuxfan** [comment]
In the future, specializations will have to implement this logic.
