### ISSUE TITLE
Determine if linear Index Space numbering starting at zero is an issue for FleCSI 

### ISSUE THREAD

**Issue by gshipman** [laristra/flecsi#263]
Jonathan's Legion/FleCSI code currently assumes that Index Spaces are numbered linearly starting at zero. Is this an issue? 

To support arbitrary numbering of index spaces Jonathan will need to utilize a map to look these up.  

Marc currently uses an enumeration  but he will have to add the colorings in the order of enumerations if we want to assume linear ordering. 

Nick will look into the runtime driver to see if this can be generalized to use a map in 15 minutes or less, otherwise he will us a vector or some other inspirational design. 

Jonathan to provide Nick with all places he makes this assumption.

**Comment by lightsighter** [comment]
@gshipman Are these Legion index space IDs (e.g. the ID inside the IndexSpace structure), or external IDs that FleCSI is assigning to index spaces made by Legion?

**Comment by tuxfan** [comment]
I think this is done.
