### ISSUE TITLE
Missing Headers in Install 

### ISSUE THREAD

**Issue by JulienLoiseau** [laristra/flecsi#284]
The missing headers are: 

flecsi/data/data_client_handle.h 
flecsi/data/legion/data_client_handle_policy.h
flecsi/topology/mesh_storage.h
flecsi/topology/legion/storage_policy.h

**Comment by JulienLoiseau** [comment]
The headers are always missing after install.

**Comment by junghans** [comment]
Hmm, 
`data/data_client_handle.h` gets installed here:
https://travis-ci.org/laristra/flecsph/jobs/248850193#L1176
`data/legion/data_client_handle_policy.h` get installed here:
https://travis-ci.org/laristra/flecsph/jobs/248850193#L1181
`topology/mesh_storage.h` gets installed here:
https://travis-ci.org/laristra/flecsph/jobs/248850193#L1228

However `topology/legion/storage_policy.h` seems to be missing...
