### ISSUE TITLE
master branch broken

### ISSUE THREAD

**Issue by jpietarilagraham** [laristra/flecsi#293]
I'm looking at hash:

 6ec8c016d487994f9bbfeb030a6def3c58357f66

and I see:

	 12 - data_client_handle (Failed)

**Comment by nickm319** [comment]
Data client handle is going to fail off and on for a while until we finally get the client handle working. I added NOCI, but I can also disable this test except for in my own working copy if it helps.

**Comment by jpietarilagraham** [comment]
OK, thanks!

**Comment by junghans** [comment]
4f9380ade7c30cc020089549fc3ea0fd2e5e34d9 was the 1st broken commit, e9e30b03a330b44da4d93786ca7881b3a577d861 was still fine.

/cc @ollielo
