### ISSUE TITLE
fix "reduction" test

### ISSUE THREAD

**Issue by ipdemes** [laristra/flecsi#299]
reduction test has inconsistent behavior and  hangs/fail on some TRAVIS builds: 
Please see https://travis-ci.org/laristra/flecsi/jobs/253404860 for an example

**Comment by jpietarilagraham** [comment]
You mean like "Running in 2a891fd33402"?  How do I login to 2a891fd33402 to attempt a debug?

**Comment by ipdemes** [comment]
@jpietarilagraham , do you have Docker installed?

**Comment by jpietarilagraham** [comment]
no.

--
Jonathan Graham
Applied Computer Science, CCS-7
(505) 665-2482 / jgraham@lanl.gov
________________________________________

**Comment by ipdemes** [comment]
Could you, please, try installing it. It should be simple on MAC: https://www.docker.com/get-docker. 
The only thing you will need to do after installation - is setting up PROXY

Then I'll send you an instructions on how to reproduce an error

**Comment by ipdemes** [comment]
@jpietarilagraham , You might want to wait: I couldn't reproduce an error myself yet (even in a Docker container)
