### ISSUE TITLE
Code formatting cleanup.

### ISSUE THREAD

**Issue by tuxfan** [laristra/flecsi#312]
Consider different options for automatically reformatting code at check-in.

**Comment by junghans** [comment]
See laristra/cinch#102

**Comment by staleyLANL** [comment]
I did a bit of work to improve code formatting back when I was working in utils/. That was the extent of my work on formatting, though.


Martin

--
Martin Staley
CCS-7, Applied Computer Science
Mail Stop B287
Los Alamos National Laboratory
Los Alamos, NM 87545
Phone: 1-505-667-7108

________________________________
