### ISSUE TITLE
Error on git clone

### ISSUE THREAD

**Issue by JulienLoiseau** [laristra/flecsi#314]
Get this error while cloning FleCSI:

fatal: reference is not a tree: a6d079862a19511228d076b4939e69a8dff4e6ac
Unable to checkout 'a6d079862a19511228d076b4939e69a8dff4e6ac' in submodule path 'cinch'

**Comment by tuxfan** [comment]
This just means that you are not up-to-date on your submodules. Usually, it is sufficient to execute:
git submodule init
git submodule update
