### ISSUE TITLE
M2 Verify Correctness

### ISSUE THREAD

**Issue by tuxfan** [laristra/flecsi#340]
Add unit tests to verify the correct function of sparse storage class.

**Comment by tuxfan** [comment]
@ollielo & @nickm319 I'm hoping that this is already done. We should meet briefly next week to discuss progress.

**Comment by ollielo** [comment]
@tuxfan, @nickm319 

This should be considered done with the unit test ```execution/test/sparse_data.cc". One thing that is not implemented is the insert more elements to the exclusive portion of the sparse data beyond the number of reserved slots.
