### ISSUE TITLE
Unresolved symbols in the FleCSI library with FLECSI_RUNTIME_MODEL=mpi

### ISSUE THREAD

**Issue by charest** [laristra/flecsi#359]
@ollielo There are unresolved symbols in the FleCSI library because flecsi::execution::runtime_driver(int, char**) is called, but not defined anywhere.  It is supposed to be defined by the user.  The way it is here you can't link to the FleCSI library without defining your own driver.  In other words, even if you are not using the execution model, you still have to define an empty driver.
 
https://github.com/laristra/flecsi/blob/3297056aa3208cf09c3bc9cb164e032874c5ce1f/flecsi/execution/mpi/context_policy.cc#L34

**Comment by ollielo** [comment]
@charest 

Is there any use case that application uses the flecsi library but not actually using the execution model?

**Comment by charest** [comment]
yes, unit testing

**Comment by ollielo** [comment]
Don't we always list runtime_driver.cc while compiling unit tests as well?

```
cinch_add_unit(client_registration
    SOURCES
      test/client_registration.cc
      data_client.cc
      ${DRIVER_INITIALIZATION}
      ${RUNTIME_DRIVER}
    DEFINES
      -DCINCH_OVERRIDE_DEFAULT_INITIALIZATION_DRIVER
    LIBRARIES
      FleCSI
      ${CINCH_RUNTIME_LIBRARIES}
    POLICY ${UNIT_POLICY}
    THREADS 2
    NOCI
    )

```

**Comment by charest** [comment]
That test uses the runtime driver.  You basically cant link to libFleCSI with some compilers right now without defining a runtime_driver.  Kinda hinders actual unit testing.
