### ISSUE TITLE
M6 Add Atomics Abstraction

### ISSUE THREAD

**Issue by tuxfan** [laristra/flecsi#363]
Add an abstraction layer to the libristra project that defines types and intrinsics for performing atomic operations.

**Comment by tuxfan** [comment]
I will add another task for creating unit tests to properly verify the interface and functionality.

**Comment by staleyLANL** [comment]
Uploaded source code and 1-page blurb to laristra/ristra/atomics/.

**Comment by staleyLANL** [comment]
Just uploaded the latest code and examples.
