### ISSUE TITLE
Initial investigation of atomics requirements and support

### ISSUE THREAD

**Issue by tuxfan** [laristra/flecsi#366]
**Task**
Research available support for floating-point atomics from existing languages and runtimes.

**Deliverables**
* A one-page summary of the findings
* Initial type and interface definitions

**Comment by tuxfan** [comment]
@staleyLANL Martin, please create a short summary (1 page) of your work to date and attach it to this issue. You can just drag and drop the .pdf file.

**Comment by tuxfan** [comment]
@staleyLANL BTW, once you have done that, you can close this issue.

**Comment by staleyLANL** [comment]
[ristra-atomics.pdf](https://github.com/laristra/flecsi/files/1769679/ristra-atomics.pdf)

**Comment by staleyLANL** [comment]
Here's what I could reasonably pack into one page. I believe it provides a good overview of what the new library is about.
