### ISSUE TITLE
Testing and enhancements to atomics interface

### ISSUE THREAD

**Issue by tuxfan** [laristra/flecsi#367]
**Task**
* Create unit tests to verify atomics operations.
* Test the atomics interface and types with all available compilers (gnu, clang, intel, ibm, etc.) to determine compatibility and support for atomics interface required language features.

**Deliverables**
* Unit test suite with coverage of new atomics interface.
* A one page summary detailing compiler support for the interface that identifies any issues with specific compilers.

**Comment by staleyLANL** [comment]
Lots of unit tests and examples. Have used clang++, g++, icc, pgc++.
