### ISSUE TITLE
replication changed reduction API, probably broke MPI

### ISSUE THREAD

**Issue by jpietarilagraham** [laristra/flecsi#374]
See test/reduction.cc: Instead of using flecsi_execute_task() to get a local future, we now use flecsi_execute_reduction_task() to get a global future.  context_.reduce_max() now takes a global future and just returns the value.  I doubt this is the API we want for the last step.  Also the reduction IDs were shoved in execution/execution.h.  A style ruling is probably needed for that.

**Comment by tuxfan** [comment]
Need to merge with feature/bergen/merged branch

**Comment by ipdemes** [comment]
fixed
