### ISSUE TITLE
Tutorial 02-data-clients works with wrong data client name

### ISSUE THREAD

**Issue by jlippuner** [laristra/flecsi#377]
In tutorial 02-data-clients the mesh is registered as follows
`flecsi_register_data_client(mesh_t, clients, mesh);`
But when I change line 56 to
`auto m = flecsi_get_client_handle(mesh_t, foo, bar);`
or any other random strings for the namespace and name of the data client whose handle I'm requesting, the example still works as normal. It compiles and runs exactly as if I do the correct thing, i.e.
`auto m = flecsi_get_client_handle(mesh_t, clients, mesh);`

Why do I still get a valid handle to the mesh even when I'm asking for a data client that does not exist?

**Comment by tuxfan** [comment]
Good question. That shouldn’t work. You should get a runtime error. I don’t have a great way to look into this right now, but I’ll try to take a look tonight. You could do a little debugging and look at what it is doing when you try to access the handle. There should be a map lookup (it should also fail).



--
Dr.-Ing. Benjamin Karl Bergen
Los Alamos National Laboratory

P.O. Box 1663, MS B287
Los Alamos, NM 87545

(505) 667-1699
________________________________

**Comment by jlippuner** [comment]
I've done some more digging. The short answer is: It appears that the map lookup only checks the `client_key`, which is essentially a hash of the data client type that does not contain any information about the data client name or namespace.

In the `get_client_handle()` method of the `data_client_policy_handler__` for mesh topologies (around line 300 in `flecsi/data/client.h`), there is a call to `storage_t::instance().assert_client_exists` (around line 320). But this assert only checks the `client_hash`, which a few lines above is defined as the hash of the data client type. It seems that the data client name and namespace that the user supplies are never used. They are part of the data client handle that is constructed, but it is not checked that the `client_registry_` map of the `storage__` class (`flecsi/data/storage.h`) actually contains a data client with that name and namespace.

So if one requests a data client handle of type T, one will get a handle as long as the `client_registry_` map contains at least one data client of type T; regardless what name or namespace one specifies when registering or getting the data client. I'm not sure whether this is intentional or a bug. I don't know whether there is a use case for distinguishing between multiple data clients of the same type (which seems to be impossible right now). But if there is no such use case, then why do we give a data client a name and namespace?

Furthermore, in this particular tutorial, the mesh actually registers itself as a data client (in file `flecsi-tutorial/specialization/mesh/mesh.cc`). So in the actual tutorial, one can comment out the `flecsi_register_data_client` line and the tutorial still works (because a data client of the mesh type has already been registered in the background). This would be very confusing for new users.

**Comment by tuxfan** [comment]
Looking at this, it is clearly broken. I'm not sure why it doesn't use the hashing functions that we put in place (this is sort of a side note.)
