### ISSUE TITLE
make_dcrs does not use TO_DIMENSION and use of THRU_DIMENSION may be incorrect

### ISSUE THREAD

**Issue by jlippuner** [laristra/flecsi#397]
`make_dcrs` in `flecsi/coloring/dcrs_utils.h` does not use the template parameter `TO_DIMENSION`. It appears that it is implicitly assumed that `TO_DIMENSION == FROM_DIMENSION`.

Also, I think that `THRU_DIMENSION` in line 174 may be used incorrectly, although the current implementation produces the correct result as long as `DIMENSION` is not more than 3. Two cells are neighbors through dimension d if they share 2^d vertices. So I think line 174 should be
`if (count.second >= (1 << THRU_DIMENSION))`
instead of
`if (count.second > THRU_DIMENSION)`

For dimensions up to 3 these are equivalent, because `>= 1` is equivalent to `> 0`, `>= 2` is equivalent to `> 1`, and `>= 4` is equivalent to `> 2` in this case, because the LHS only takes on values 0, 1, 2, 4. But if the dimension is 4 or more, the current implementation would return neighbors that are connected through a smaller dimension than the specified `THRU_DIMENSION`. For example, in `DIMENSION = 4`, cells that share 8 vertices with one another are connected through dimension 3 and cells that share 4 vertices are connected through dimension 2. So for `THRU_DIMENSION = 3`, the current implementation would return cells connected through dimensions 2 and 3 instead of only 3.

**Comment by charest** [comment]
What is the use case for DIMENSION>3?  Because other stuff will break.

**Comment by jlippuner** [comment]
I don't have a specific use case for `DIMENSION > 3` in mind, and maybe there isn't one. I was just confused by how `THRU_DIMENSION` is currently used in the code, since it appears to be a hack that only works for `DIMENSION <= 3`. I think it would be worthwhile to have a general implementation that makes as few assumptions as possible, especially if the change is so minor and would enhance the readability.

**Comment by charest** [comment]
I dont think there truly is a general implementation, or at least an easy one.  I don't think this would work if you wanted a naive partitioning of vertices.

And I would argue that 
 `if (count.second > THRU_DIMENSION)`
is easier to read than
 `if (count.second >= (1 << THRU_DIMENSION))`

**Comment by ollielo** [comment]
You are totally correct. make_dcrs was over-designed to find the entity to
entity connectivity from any dimension to any dimension through any
dimension for the whole mesh. It required an O(n^2) (or worse?) search that
when used to partition some sample mesh for FleCSale, it took several
hours. AFAIK, the only use case for make_dcrs is to create cell to cell
connectivity (i.e. the dual graph)  as input for ParMetis, thus I changed
it to just work for the case of TO_DIMENSION == FROM_DIMENSION.

The template parameter THRU_DIMENSION is also a misnomer. As I put in the
comment, it is actually the number of shared vertices between entities of
different dimensions. It was never thought or tested to work with anything
of a dimension of 4 or higher.

How would you modify the logic for it work with higher dimensional cells?

Ollie

**Comment by jlippuner** [comment]
Makes sense. In that case, I would suggest to remove TO_DIMENSION from the template parameters or add an `assert(TO_DIMENSION == FROM_DIMENSION)` with explanation.

I realize now that my proposed solution only works for Cartesian meshes, where two cells connected through dimension D always share 2^D vertices. But I think this is not true for an arbitrary mesh. In 3 dimensions, if two cells share 4 vertices, they could be connected through dimension 2 if they are rectangular boxes and share a face consisting of 4 vertices, or they could be connected through dimension 3 if they're tetrahedrons and are thus identical since they share all 4 vertices.

Similarly, in 4 dimensions, for 4-simplexes to be connected through dimension 3, they have to share 4 vertices, but for hypercubes to be connected through dimension 3, they have to share 8 vertices.

So maybe the best solution would be to add an `assert(DIMENSION <= 3)` and if someone wants to use higher dimensional meshes, they would have to provide their own implementation of `make_dcrs` that is specific to the mesh.

**Comment by tuxfan** [comment]
This is not designed to handle dimensions higher than 3.
