### ISSUE TITLE
Template type naming in conflict with C++ standard

### ISSUE THREAD

**Issue by hr87** [laristra/flecsi#400]
I have a remark on the naming guide lines for template types. According to the developer guide, template type names should end with a double underscore. However, according to the C++ standard ([C++17 standard](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4659.pdf), section 5.10.3), all identifiers with a double underscore are reserved for the compiler implementation:

> In addition, some identifiers are reserved for use by C++ implementations and shall not be used otherwise; no diagnostic is required.
> — Each identifier that contains a double underscore __ or begins with an underscore followed by an uppercase letter is reserved to the implementation for any use.
> — Each identifier that begins with an underscore is reserved to the implementation for use as a name in the global namespace.

Therefore, type names with double underscore can cause hard to identify errors during the compiler run in current or future compiler implementations.

**Comment by tuxfan** [comment]
We will change this to use _u for "unqualified"
