### ISSUE TITLE
error in flecsi execution/mpi/task_prolog.h: invalid conversion...

### ISSUE THREAD

**Issue by timmah** [laristra/flecsi#407]
Getting several instances of the following with GCC 7.3.0:

    flecsi/execution/mpi/task_prolog.h:250:95: error: invalid conversion from ‘size_t* {aka long unsigned int*}’ to ‘uint64_t* {aka long long unsigned int*}’ [-fpermissive]
             adj.indices_buf = reinterpret_cast<size_t *>(registered_field_data[adj.index_fid].data());

Also at line 277, same file. These come about when building the flecsi-tutorial.

Also getting these with Clang 6.0. This is on OSX 10.13. 

Basically, the lhs of the assignment is uint64_t *, while the rhs is size_t *. 

Full message:

    [  0%] Building CXX object CMakeFiles/FleCSI-Tut.dir/flecsi-tutorial/specialization/mesh/control_points.cc.o
    g++  -DFLECSI_DBC_THROW -DFLECSI_REQUIRE_ON -DFleCSI_Tut_EXPORTS -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX -I/path/to/flecsi/branches/master -I/path/to/flecsi/builds/master/gcc-7.3.0 -I/path/to/flecsi/branches/master/cinch/boost/preprocessor/include -I/path/to/openmpi-2.0.1/include -I/path/to/flecsi/branches/master/cinch/logging -I/path/to/install/clang-6.0/include -I/path/to/flecsi/branches/master/flecsi -I/path/to/flecsi/builds/master/gcc-7.3.0/flecsi -I/path/to/flecsi/branches/master/flecsi/.. -I/path/to/flecsi/builds/master/gcc-7.3.0/flecsi/.. -I/path/to/flecsi/branches/master/flecsi-tutorial/specialization -I/path/to/flecsi/builds/master/gcc-7.3.0/flecsi-tutorial/specialization -I/path/to/flecsi/branches/master/flecsi-tutorial/specialization/.. -I/path/to/flecsi/builds/master/gcc-7.3.0/flecsi-tutorial/specialization/..  -std=c++14 -O3 -DNDEBUG -fPIC   -o CMakeFiles/FleCSI-Tut.dir/flecsi-tutorial/specialization/mesh/control_points.cc.o -c/path/to/flecsi/branches/master/flecsi-tutorial/specialization/mesh/control_points.cc
    In file included from/path/to/flecsi/branches/master/flecsi/execution/mpi/execution_policy.h:27:0,
                     from/path/to/flecsi/branches/master/flecsi/runtime/flecsi_runtime_execution_policy.h:43,
                     from/path/to/flecsi/branches/master/flecsi/execution/function.h:87,
                     from/path/to/flecsi/branches/master/flecsi/execution/execution.h:23,
                     from/path/to/flecsi/branches/master/flecsi-tutorial/specialization/mesh/control_points.cc:17:
    /path/to/flecsi/branches/master/flecsi/execution/mpi/task_prolog.h: In instantiation of ‘std::enable_if_t<std::is_base_of<flecsi::topology::mesh_topology_base_t, T>::value> flecsi::execution::task_prolog_t::handle(flecsi::data_client_handle__<T, PERMISSIONS>&) [with T = flecsi::tutorial::specialization_mesh_t; long unsigned int PERMISSIONS = 2; std::enable_if_t<std::is_base_of<flecsi::topology::mesh_topology_base_t, T>::value> = void; flecsi::data_client_handle__<T, PERMISSIONS> = flecsi::data_client_handle_base__<flecsi::tutorial::specialization_mesh_t, 2, flecsi::mpi_data_client_handle_policy_t>]’:
    /path/to/flecsi/branches/master/flecsi/utils/tuple_walker.h:51:5:   required from ‘static std::size_t flecsi::utils::tuple_walker_helper__<INDEX, TUPLE_TYPE, CRTP_TYPE>::walk(CRTP_TYPE&, TUPLE_TYPE&) [with long unsigned int INDEX = 1; TUPLE_TYPE = std::tuple<flecsi::data_client_handle_base__<flecsi::tutorial::specialization_mesh_t, 2, flecsi::mpi_data_client_handle_policy_t> >; CRTP_TYPE = flecsi::execution::task_prolog_t; std::size_t = long unsigned int]’
    /path/to/flecsi/branches/master/flecsi/utils/tuple_walker.h:123:22:   required from ‘void flecsi::utils::tuple_walker__<CRTP_TYPE>::walk(TUPLE_TYPE&) [with TUPLE_TYPE = std::tuple<flecsi::data_client_handle_base__<flecsi::tutorial::specialization_mesh_t, 2, flecsi::mpi_data_client_handle_policy_t> >; CRTP_TYPE = flecsi::execution::task_prolog_t]’
    /path/to/flecsi/branches/master/flecsi/execution/mpi/execution_policy.h:194:5:   required from ‘static decltype(auto) flecsi::execution::mpi_execution_policy_t::execute_task(ARGS&& ...) [with flecsi::execution::launch_type_t launch = (flecsi::execution::launch_type_t)0; long unsigned int KEY = 4924432441684412972; RETURN = void; ARG_TUPLE = std::tuple<flecsi::data_client_handle_base__<flecsi::tutorial::specialization_mesh_t, 2, flecsi::mpi_data_client_handle_policy_t> >; ARGS = {flecsi::data_client_handle_base__<flecsi::tutorial::specialization_mesh_t, 0, flecsi::mpi_data_client_handle_policy_t>&}]’
    /path/to/flecsi/branches/master/flecsi/execution/task.h:94:17:   required from ‘static decltype(auto) flecsi::execution::task_interface__<EXECUTION_POLICY>::execute_task(ARGS&& ...) [with flecsi::execution::launch_type_t launch = (flecsi::execution::launch_type_t)0; long unsigned int KEY = 4924432441684412972; RETURN = void; ARG_TUPLE = std::tuple<flecsi::data_client_handle_base__<flecsi::tutorial::specialization_mesh_t, 2, flecsi::mpi_data_client_handle_policy_t> >; ARGS = {flecsi::data_client_handle_base__<flecsi::tutorial::specialization_mesh_t, 0, flecsi::mpi_data_client_handle_policy_t>&}; EXECUTION_POLICY = flecsi::execution::mpi_execution_policy_t]’
    /path/to/flecsi/branches/master/flecsi-tutorial/specialization/mesh/control_points.cc:77:3:   required from here
    /path/to/flecsi/branches/master/flecsi/execution/mpi/task_prolog.h:250:95: error: invalid conversion from ‘size_t* {aka long unsigned int*}’ to ‘uint64_t* {aka long long unsigned int*}’ [-fpermissive]
             adj.indices_buf = reinterpret_cast<size_t *>(registered_field_data[adj.index_fid].data());
                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
    /path/to/flecsi/branches/master/flecsi/execution/mpi/task_prolog.h:277:11: error: invalid conversion from ‘size_t* {aka long unsigned int*}’ to ‘uint64_t* {aka long long unsigned int*}’ [-fpermissive]
               reinterpret_cast<size_t *>(registered_field_data[iss.index_fid].data());

**Comment by ollielo** [comment]
@timmah ,

I looked into the type of indices_buf as defined in `data_client_handle_adjacency_t` and `data_client_handle_index_subspace_t` and how they are actually used. Now I don't think either `size_t *` nor `uint64_t` is correct. The buffer pointed by indices_buf is later used to be pass to `init_connectivity()` and `init_index_subspace()` to store `utils::id_t` which is 128 bits in size. I think we have to change both the type cast here and the pointer types in both   `data_client_handle_adjacency_t` and `data_client_handle_index_subspace_t`.

@nickm319 

How do you think about this?

**Comment by timmah** [comment]
@nickm319 @ollielo  Nick, have you had a chance to look at this?

**Comment by nickm319** [comment]
Ollie and I discussed a potential fix for this.  I will see if I can make the change now.

**Comment by nickm319** [comment]
Thanks for bringing this to my attention again. Tim, can you see if my push to master just now fixes the compiler error you were seeing? Thanks.

Nick

From: First name Last name <nickm@lanl.gov<mailto:nickm@lanl.gov>>
Date: Friday, June 22, 2018 at 10:24 AM
To: laristra/flecsi <reply@reply.github.com<mailto:reply@reply.github.com>>, laristra/flecsi <flecsi@noreply.github.com<mailto:flecsi@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: Re: [laristra/flecsi] error in flecsi execution/mpi/task_prolog.h: invalid conversion... (#407)

Ollie and I discussed a potential fix for this.  I will see if I can make the change now.

**Comment by timmah** [comment]
That did it, thanks. Closing.
