### ISSUE TITLE
Ghost copy not initiated for mpi_tasks

### ISSUE THREAD

**Issue by jpietarilagraham** [laristra/flecsi#419]
So, I've been working on a climate coupler in FleCSI and have run across an interesting FleCSI feature: I'm reading data via a mpi task (to use netcdf) and I give that task a data handle/accessor.  The following lines do not get executed for such an mpi task: https://github.com/laristra/flecsi/blob/master/flecsi/execution/legion/execution_policy.h#L355-L368

This means that even though I populate shared data into a legion region in the mpi task, it is never copied to ghost.

**Comment by ipdemes** [comment]
@jpietarilagraham : I though you have fixed that. Can we close the issue?
