### ISSUE TITLE
Runtime failures in laristra/flecsi-tutorial:legion image

### ISSUE THREAD

**Issue by dmringo** [laristra/flecsi#420]
Update 2018-10-25: This is still an issue @ipdemes.  The failure mode has changed, but it's still a problem at runtime:

`flecsit` in the Docker image for the FleCSI tutorial with Legion produces binaries that fail with Illegal Instructions.  This happens invariable for the first nine examples.

To reproduce for e.g. the first tutorial:
1. `docker pull laristra/flecsi-tutorial:legion`
2. `docker run -it -h tutorialhost -u flecsi laristra/flecsi-tutorial:legion /bin/bash`
3. `module load flecsi-tutorial`
4. `cd flecsi-tutorial/00-driver`
5. `flecsit compile -v driver.cc`
6. `./driver`

To verify all nine at once:

1. `shopt -s extglob`
2. `for dir in 0[0-8]!(*-control-model); do cd "$dir"; flecsit compile "${dir#*-}.cc" && ./"${dir#*-}"; cd ..; done`

This produces a lot of compilation output, but you should be able to see that each binary invoked fails in the same way with `Illegal instruction (core dumped)`

**Comment by tuxfan** [comment]
@tuxfan will review this issue.

**Comment by ipdemes** [comment]
@dmringo : what machine are you using ?

**Comment by dmringo** [comment]
@ipdemes This is running in a `flecsi-tutorial:legion` docker container based on Fedora 28.  The host (my machine) is running Antergos with kernel version 5.0.7.

It's worth pointing out that the flecsi-tutorial image was last built 8 months ago on Docker Hub, so it's likely using a fairly old laristra/FleCSI stack.
