### ISSUE TITLE
flecsit does not work with Legion backend

### ISSUE THREAD

**Issue by jlippuner** [laristra/flecsi#427]
There are missing include paths (for legion.h, for example) when using `flecsit` to compile a tutorial with the Legion backend. I have Legion installed in `flecsi-3rd-party-install` but FleCSI itself is installed in a different directory. `flecsit` does have all the necessary include directories in the `build` dictionary, but that field never gets used in `flecist/services/compile_driver/execute.py`. The only include directories passed to CMake are the ones contained in `${FLECSI_INCLUDE_DIRS}`, which doesn't include the necessary 3rd-party includes.

Changing line 64 of `flecist/services/compile_driver/execute.py` to
`cxx_flags = '-DCMAKE_CXX_FLAGS=' + build['flags'] + " " + build['includes']`
fixes the issue, but I don't know whether this should be fixed in `flecsit` or in `${FLECSI_INCLUDE_DIRS}`.

**Comment by tuxfan** [comment]
@tuxfan will look into this.
