### ISSUE TITLE
MPI backend: Sparse mutator cannot be used more than once

### ISSUE THREAD

**Issue by jlippuner** [laristra/flecsi#429]
I adapted the `sparse_data` test to also test mutating the sparsity pattern after it is set initially (see my `feature/jlippuner/improve_tests` branch). With the MPI backend, I kept getting segfaults the second time I tried to use the sparse mutator. Then I saw line 288 (247 after clang-format) in `execution/mpi/task_epilog.h`, which says
```
delete h.num_exclusive_insertions;
```
Commenting out this line makes the test work as expected. However, I'm not sure whether I can just comment it out or whether I should do
```
*h.num_exclusive_insertions = 0;
```
instead.

**Comment by ollielo** [comment]
@jlippuner 

I do think this is a bug, however I don't remember why @nickm319 used a point with new'd space for num_exclusive_insertions, otherwise I would just change it the an size_t object rather than a pointer.

@nickm319 , do you remember why it is a pointer?

**Comment by cferenba** [comment]
The workaround that is in place seems to be working properly.  The `sparse_data` unit test reuses a sparse mutator with no problem.
