### ISSUE TITLE
update docs:  c++17 now required?

### ISSUE THREAD

**Issue by cferenba** [laristra/flecsi#453]
Does flecsi now require c++17 to compile?  I tried compiling the current master against gcc 6.4.0 and got a build error for an inline variable, which is new to c++17.  I had to move up to gcc 7.3.0 to build.

If c++17 is required now, the README needs to be updated accordingly.

Edit:  I thought I recalled seeing a commit from @ktsai7 to upgrade to c++17, but I can't find that commit now.

**Comment by ktsai7** [comment]
Yes, Ben updated FleCSI to C++17 few weeks (months?) ago. Then libristra got up to C++17 shortly after by someone else, so I did a commit to update the cinch module for compilation problems that we started having.

I will go through and update FleCSI README accordingly.
@tuxfan Is there anywhere else that might need to be double checked other than READMEs?

**Comment by cferenba** [comment]
Thanks.  Note that in addition to changing c++14 -> c++17, we also need gcc 6 -> gcc 7.
