### ISSUE TITLE
Static Analysis Milestone Description

### ISSUE THREAD

**Issue by tuxfan** [laristra/flecsi#463]
- Work with Ristra team to identify gaps in our current static analysis capability, and to improve the FleCSI interface when possible.
- Implement a static analysis tool for identifying runtime errors statically.
- Integrate static analysis tool into FleCSI project (build system, test, and invocation).

**Comment by staleyLANL** [comment]
Static analysis tool is fully functional and usable now.
The concept of "analysis" is very open-ended, and we'll no doubt come up with more viable things to analyze and detect, over time.
I've put out queries to users regarding what they'll want.
Integration into the build system shouldn't be difficult. We note that the tool, called flecstan, does not require FleCSI itself, for its build; it needs only the clang/llvm tooling libraries. It also doesn't (or rather doesn't need to) analyze FleCSI's code base; rather, it would analyze user code that links with FleCSI.
