### ISSUE TITLE
Build with gcc-4.9 is broken

### ISSUE THREAD

**Issue by junghans** [laristra/flecsi#47]
@tuxfan : Flecsi builds fine with gcc-5, but build with gcc-4.9 is broken:
https://travis-ci.org/junghans/flecsi/jobs/124569585

Do we want to drop support for gcc-4.9?

**Comment by ollielo** [comment]
Multi-line constexpr function is C++14. Did you enable the right flag?

If the correct flag is set, it is also possible that gcc-4.9 has broken C++14 support. If that's the case, we should drop gcc-4.9.

**Comment by junghans** [comment]
Obsolete.
