### ISSUE TITLE
sparse data accessor

### ISSUE THREAD

**Issue by mattbement** [laristra/flecsi#516]
If there is no entry for a given index, the operator()(size_t index, size_t entry) catches this in an assertion and aborts.  Is there a better way to find out if an entry exists for an index?  Better yet, could a default value be provided when a sparse array is set up, which would get returned when no entry is found for a given index?

**Comment by cferenba** [comment]
As part of #531, which just got merged yesterday, I added the `contains` method, which tests whether a given entry exists for a given index.  This should do what you need.  Let me know if you have any problems with it.
