### ISSUE TITLE
Error Building FleCSI with Spack

### ISSUE THREAD

**Issue by wspear** [laristra/flecsi#525]
Installing FleCSI with spack using MPICH 3.2.1 and GCC 7.2.0 results in several errors. The command used to install is `spack install flecsi^mpich@3.2.1%gcc@7.3.0`. The error output is contained in this file: 
http://nic.uoregon.edu/~wspear/tmp/flecsi-spack.txt

Many of the errors are of the form:
runtime_driver.cc:287:23: error: 'struct Legion::MustEpochLauncher' has no member named 'launch_domain'

**Comment by tuxfan** [comment]
@junghans, can you take look at this issue. It could be so old that it is no longer relevant.
