### ISSUE TITLE
Thoughts on [sometimes strange/unexpected] content in utils/id.h

### ISSUE THREAD

**Issue by staleyLANL** [laristra/flecsi#580]
I've been looking at class id_ in utils/id.h, which is used elsewhere in FleCSI through flecsi::utils::id_t in utils/common.h, defined thus:

     using id_t = id_<20,40,4,60>;

in namespace flecsi::utils::. As used, then, id_ amounts to a 128-bit value as follows:

     ddmmppppppppppppppppppppeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
     ffffgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg

where {d=dimension, m=domain, p=partition, e=entity, f=flags, g=global}.

My impression is that the class may originally have been designed with its bit fields in a different order, or perhaps have had a non-bitfield implementation. Consider the local_id() member function. For an id_ value as sketched above, local_id() produces:

     eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeppppppppppppppppppppmmdd

i.e. with flags and global thrown out (probably intended, given the name local_id()), but also with the {dimension,domain,partition,entity} blocks reversed. Unless I can find a necessary reason somewhere for id_'s internal bitfield ordering, or local_id()'s reordering thereof, then making them consistent with one another, instead of reversed, could simplify local_id() and improve its performance.

The == operator appears to be wrong, although in a manner that likely wouldn't have arisen in any current FleCSI code. It does the following:

     return (local_id() & FLAGS_UNMASK) == (id.local_id() & FLAGS_UNMASK);

and each side of the == amounts to:

     eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeppppppppppppppppppppmmdd
     &
     1000011111111111111111111111111111111111111111111111111111111111

Why would we 0-out those four (almost-)high-order bits of entity?? Given that the 10000... value is from something called FLAGS_UNMASK, my impression is that the four 0s were originally intended to mask out the four "flags" bits (ffff). But those, in fact, would already have tossed by local_id() (see above).

Note also that != isn't equivalent to !(==), although this wouldn't have shown up in a current, realistic code. This is almost certainly unintended. If for whatever reason someone really wanted inconsistent == and != operators, then that should be reconsidered! :-/

My impression is that both of the &s with FLAGS_UNMASK, in operator==, just shouldn't be there. (And then FLAGS_UNMASK can be chucked - it isn't used elsewhere).

Is anyone familiar enough with the provenance of utils/id.h that s/he can provide some thoughts about what might have been the intention of some of its behavior? I think I can "fix" it safely, but, with code like this, I'd like to be extra careful before doing so. I generally like to assume that someone had a good reason for doing something, even if it appears to be wrong.

**Comment by staleyLANL** [comment]
@tuxfan just pinging you on this issue, so you can be aware that I'm making some internal changes to utils::id_, which is substantially used elsewhere in the code. Per the above description, id_ at present contains things that I believe are almost certainly wrong, although it's often hard to be certain of that without knowing the original author's intention. I'll make some more changes, and be sure the CI passes.

**Comment by tuxfan** [comment]
Nick wrote the original id stuff. At the time, we thought that we would have to store information about the partitioning, dimension, domain, and local id in the id type. This didn't turn out to make sense. We can meet to discuss your findings, but the ultimate goal is to purge anything that isn't used.

**Comment by staleyLANL** [comment]
OK, sounds good. I've purged much of the unused stuff, and tried tweaking the code to clarify the remaining content. See the fix/staley/utils-id branch. There may be a bit more that can go, but need to be careful with this sort of thing. At this point I just need to check against flecsale-mm, and whatever other external apps might potentially be affected by such low-level changes. The python "register" issue is fixed now, so I'm close to verifying that flecsale-mm still works (or that it fails, but I hope that doesn't happen) with the ID changes. Will do the same for the iterator cleanup on the staley/feature/cleanup branch (I know, shoulda called it iterator-cleanup, and transposed staley and feature :-) ).
