### ISSUE TITLE
False coverage rate of Codecov/GGov

### ISSUE THREAD

**Issue by ollielo** [laristra/flecsi#90]
Because FleCSI is a header-only, template library, a large portion of the code base does not get instantiated if there is no corresponding unit tests. As GCov only takes instantiated code into account, this gives unreasonable and false test coverage rate as currently reported by Codecov. Thus we have to:
1. Keep in mind the coverage rate is **not thrustworthy**
2. Find right gcc/gcov flags or other tools for reporting coverage rate.
3. Adopt a test first practice (i.e. TDD) to increase true coverage of unit tests.

**Comment by charest** [comment]
I don't understand what you want me to do?

**Comment by ollielo** [comment]
I don't know the particular reason Christoph assigned is issue to you. However, I created this issue to make team members to be aware of some pitfalls of our current software engineering  tools and process. We can discussion the details in our next meeting.

**Comment by junghans** [comment]
I guess this is more a bug in GCov than flecsi ;-)
